repository:
  name: confidence-to-move-fast-slides
  description: >-
    Spectacle slide deck for talk about having the confidence for
    continuous-deployment
  homepage: https://confidence-to-move-fast.travi.org/
  private: false
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: breaking change
    color: e0fc28
  - name: greenkeeper
    color: 00c775
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
collaborators:
  - username: travi-bot
    permission: push
